In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df= pd.read_csv('loan_data.csv')
df.head()

person_age person_gender person_education  person_income  person_emp_exp  \
0        22.0        female           Master        71948.0               0   
1        21.0        female      High School        12282.0               0   
2        25.0        female      High School        12438.0               3   
3        23.0        female         Bachelor        79753.0               0   
4        24.0          male           Master        66135.0               1   

  person_home_ownership  loan_amnt loan_intent  loan_int_rate  \
0                  RENT    35000.0    PERSONAL          16.02   
1                   OWN     1000.0   EDUCATION          11.14   
2              MORTGAGE     5500.0     MEDICAL          12.87   
3                  RENT    35000.0     MEDICAL          15.23   
4                  RENT    35000.0     MEDICAL          14.27   

   loan_percent_income  cb_person_cred_hist_length  credit_score  \
0                 0.49                         3.0           561   
1                 0.08                         2.0           504   
2                 0.44                         3.0           635   
3                 0.44                         2.0           675   
4                 0.53                         4.0           586   

  previous_loan_defaults_on_file  loan_status  
0                             No            1  
1                            Yes            0  
2                             No            1  
3                             No            1  
4                             No            1

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['person_gender']=le.fit_transform(df['person_gender'])
df['person_home_ownership']=le.fit_transform(df['person_home_ownership'])
df['loan_intent']=le.fit_transform(df['loan_intent'])
df['previous_loan_defaults_on_file']=le.fit_transform(df['previous_loan_defaults_on_file'])
df['person_education'] = le.fit_transform(df['person_education'])
df.head()

person_age  person_gender  person_education  person_income  person_emp_exp  \
0        22.0              0                 4        71948.0               0   
1        21.0              0                 3        12282.0               0   
2        25.0              0                 3        12438.0               3   
3        23.0              0                 1        79753.0               0   
4        24.0              1                 4        66135.0               1   

   person_home_ownership  loan_amnt  loan_intent  loan_int_rate  \
0                      3    35000.0            4          16.02   
1                      2     1000.0            1          11.14   
2                      0     5500.0            3          12.87   
3                      3    35000.0            3          15.23   
4                      3    35000.0            3          14.27   

   loan_percent_income  cb_person_cred_hist_length  credit_score  \
0                 0.49                         3.0           561   
1                 0.08                         2.0           504   
2                 0.44                         3.0           635   
3                 0.44                         2.0           675   
4                 0.53                         4.0           586   

   previous_loan_defaults_on_file  loan_status  
0                               0            1  
1                               1            0  
2                               0            1  
3                               0            1  
4                               0            1

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df_scaled = sc.fit_transform(df)
df_scaled = pd.DataFrame(df_scaled, columns=df.columns)
df_scaled.head()

person_age  person_gender  person_education  person_income  person_emp_exp  \
0   -0.953538      -1.110069          1.525264      -0.104090       -0.892284   
1   -1.118963      -1.110069          0.849192      -0.846005       -0.892284   
2   -0.457264      -1.110069          0.849192      -0.844065       -0.397517   
3   -0.788113      -1.110069         -0.502953      -0.007039       -0.892284   
4   -0.622689       0.900845          1.525264      -0.176371       -0.727362   

   person_home_ownership  loan_amnt  loan_intent  loan_int_rate  \
0               0.904822   4.024953     0.852919       1.683039   
1               0.210609  -1.359209    -0.882904       0.044782   
2              -1.177817  -0.646600     0.274312       0.625557   
3               0.904822   4.024953     0.274312       1.417829   
4               0.904822   4.024953     0.274312       1.095549   

   loan_percent_income  cb_person_cred_hist_length  credit_score  \
0             4.016394                   -0.739109     -1.419814   
1            -0.684829                   -0.996863     -2.549975   
2             3.443074                   -0.739109      0.047412   
3             3.443074                   -0.996863      0.840507   
4             4.475050                   -0.481354     -0.924130   

   previous_loan_defaults_on_file  loan_status  
0                       -1.016040     1.870829  
1                        0.984213    -0.534522  
2                       -1.016040     1.870829  
3                       -1.016040     1.870829  
4                       -1.016040     1.870829

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
X=df_scaled.drop('loan_status', axis=1).values
y=df['loan_status'].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [ ]:
lr.fit(X_train,y_train)

LogisticRegression()

In [ ]:
lr.predict(X_test)

array([0, 0, 1, ..., 1, 1, 1])

In [ ]:
lr.coef_

array([[ 2.44823658e-01,  1.01262969e-02, -2.79389569e-03,
         2.90162459e-02, -1.94154745e-01,  3.50408049e-01,
        -5.50920490e-01, -2.74900348e-01,  9.89025728e-01,
         1.27518970e+00, -2.74846284e-02, -4.54869143e-01,
        -4.52013808e+00]])

In [ ]:
lr.intercept_

array([-5.26176366])

In [ ]:
class MyPerceptron:
  def __init__(self, learning_rate=0.01, epoch=100):
    self.intercept_ = 0
    self.coef_ = None
    self.lr = learning_rate
    self.epoch = epoch

  def step_function(self, z):
    return np.where(z >= 0, 1, 0)

  def fit(self, X_train, y_train):
    X_train = np.insert(X_train, 0, 1, axis=1)
    weights = np.ones(X_train.shape[1])

    for i in range(self.epoch):
        j = np.random.randint(0, X_train.shape[0])
        y_hat = self.step_function(np.dot(X_train[j], weights))
        weights = weights + self.lr * (y_train[j] - y_hat) * X_train[j]

    self.intercept_ = weights[0]
    self.coef_ = weights[1:]

    print(self.intercept_, self.coef_)

  def predict(self, X_test):
    linear_output = np.dot(X_test, self.coef_) + self.intercept_
    return self.step_function(linear_output)

In [ ]:
mp = MyPerceptron(learning_rate=0.1, epoch=1000000)

In [ ]:
mp.fit(X_train, y_train)

-5.899999999999995 [ 0.33380546  0.21363881  0.07590364 -0.16763938 -0.03384786 -0.03667258
 -0.22010083  0.03302279  0.34858456  0.45077937 -0.06048675 -0.08256681
 -5.19099705]


In [ ]:
mp.predict(X_test)

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, mp.predict(X_test))

0.5543266102797658